#server:
#  port: 11666


spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiliao?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    #虚拟机
    #    password: zhemima666

    # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0

#    password: root
    # 虚拟机密码
    password: zhemima666
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  #修改mvc路径匹配规则
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  #email
  mail:
    protocol: smtp
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 发送者邮箱，已开通POP3/SMTP服务的邮箱，也就是你自己的
    username: javazhirui@163.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: MDPKODGIQPOSMPNQ
    # 端口号465或587（QQ邮箱发送邮件仅支持587端口协议）
    #    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8


    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis:
  config-location: classpath:mybatis/mybatis.xml
#  mapper-locations: classpath:mapper/*Mapper.xml



mybatis-plus:
  configuration:
    #开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes:
  # 匹配链接
  urlPatterns:


#freemarker
freemarker:
  allow-request-override: false
  cache: true
  check-template-location: false
  charset: UTF-8
  content-type: text/html;charset=utf-8
  expose-request-attributes: false
  expose-session-attributes: false
  expose-spring-macro-helpers: fase
  request-context-attribute:
    suffix: .ftl
    template-loader-path: classpath:/templates/


shangChuanYuLanTime: 60

shiliaoFilePath:
  #验证码地址
#  codeImgPath: D:/ShiLiao/CodeImg/
  codeImgPath: /usr/local/app/shiliao/CodeImg/
  #用户信息导出地址
  #  userMessageExcelPath: D:/ShiLiao/userMessageExcel/
  userMessageExcelPath: /usr/local/app/shiliao/userMessageExcel/
  #病历信息excel导出地址
  #  casesMessageExcelPath: D:/ShiLiao/casesMessageExcel/
  casesMessageExcelPath: /usr/local/app/shiliao/casesMessageExcel/
  #病历信息word导出地址
  #  casesMessageWordPath: D:/ShiLiao/casesMessageWord/
  casesMessageWordPath: /usr/local/app/shiliao/casesMessageWord/
  #食用疗程影像及诊断图片上传地址
  #  casesUrlPath: D:/ShiLiao/casesVideo_casesImg/
  casesUrlPath: /usr/local/app/shiliao/casesVideo_casesImg/


#redis缓存时间
shiliaoRedisTime:
  #图片验证码有效时长(秒)
  codeTime: 3000
  #邮箱验证码有效时长(秒)
  emailCodeTime: 3000

  phoneCodeTime: 3000


#jwt过期时间(秒)
jwtDeadTime: 300000


## Miniio配置
#minio:
#  #外网访问服务地址
#  url: http://47.94.216.226:9000
#  endpoint: localhost
#  #  accessKey: admin
#  #  secretKey: zhemima666
#  accessKey: yQtSg8dkioa6my8N
#  secretKey: 4AyGZ9rxiFUIif3njzUJ2dRUpzaOj6RE
#  bucketName: shiliao
#  previewUrl: http://47.94.216.226:9000
minio:
  #外网访问服务地址
  endpoint: http://47.94.216.226:9000
  #minio账号
  accessKey: pbxkPAFL0A8WeSHV
  #minio密码
  secretKey: CHnbYbgVCki4FMHUjniRuprsUV2Cehah
  bucketName: shiliao

